"""Polars Metrics - Native Polars metrics library for quantitative finance.

A complete QuantStats replacement with native Polars implementation.
"""

from polars_metrics._version import __version__
from polars_metrics.config import DEFAULT_CONFIG, MetricsConfig, get_config, set_config
from polars_metrics.core import (
    # Returns
    avg_loss,
    avg_return,
    avg_win,
    best,
    cagr,
    comp,
    consecutive_losses,
    consecutive_wins,
    payoff_ratio,
    profit_factor,
    win_rate,
    worst,
    # Risk
    cvar,
    downside_deviation,
    max_drawdown,
    to_drawdown_series,
    ulcer_index,
    var,
    volatility,
    # Performance
    benchmark_correlation,
    calmar,
    common_sense_ratio,
    gain_to_pain_ratio,
    greeks,
    information_ratio,
    kelly_criterion,
    omega,
    r_squared,
    recovery_factor,
    risk_return_ratio,
    sharpe,
    sortino,
    tail_ratio,
    treynor_ratio,
    ulcer_performance_index,
    # Distribution
    expected_return,
    geometric_mean,
    jarque_bera,
    kurtosis,
    outlier_loss_ratio,
    outlier_win_ratio,
    shapiro_wilk,
    skewness,
    # Rolling
    rolling_beta,
    rolling_sharpe,
    rolling_sortino,
    rolling_volatility,
)
from polars_metrics.advanced import (
    # Trading metrics
    adjusted_sortino,
    cpc_index,
    expectancy,
    exposure,
    ghpr,
    k_ratio,
    rar,
    risk_of_ruin,
    serenity_index,
    smart_sharpe,
    smart_sortino,
    sqn,
)
from polars_metrics.exceptions import (
    BenchmarkMismatchError,
    EmptySeriesError,
    InsufficientDataError,
    InvalidFrequencyError,
    MetricsError,
)
from polars_metrics.reports import (
    MetricsReport,
    full_metrics,
    generate_html_report,
    metrics_summary,
    save_html_report,
)

__all__ = [
    "__version__",
    # Config
    "MetricsConfig",
    "DEFAULT_CONFIG",
    "get_config",
    "set_config",
    # Exceptions
    "MetricsError",
    "EmptySeriesError",
    "InsufficientDataError",
    "BenchmarkMismatchError",
    "InvalidFrequencyError",
    # Returns
    "comp",
    "cagr",
    "avg_return",
    "avg_win",
    "avg_loss",
    "best",
    "worst",
    "win_rate",
    "payoff_ratio",
    "profit_factor",
    "consecutive_wins",
    "consecutive_losses",
    # Risk
    "volatility",
    "var",
    "cvar",
    "max_drawdown",
    "to_drawdown_series",
    "ulcer_index",
    "downside_deviation",
    # Performance
    "sharpe",
    "sortino",
    "calmar",
    "omega",
    "gain_to_pain_ratio",
    "ulcer_performance_index",
    "kelly_criterion",
    "tail_ratio",
    "common_sense_ratio",
    "risk_return_ratio",
    "recovery_factor",
    # Benchmark metrics
    "greeks",
    "information_ratio",
    "r_squared",
    "treynor_ratio",
    "benchmark_correlation",
    # Distribution metrics
    "skewness",
    "kurtosis",
    "jarque_bera",
    "shapiro_wilk",
    "outlier_win_ratio",
    "outlier_loss_ratio",
    "expected_return",
    "geometric_mean",
    # Rolling metrics
    "rolling_volatility",
    "rolling_sharpe",
    "rolling_sortino",
    "rolling_beta",
    # Trading metrics
    "exposure",
    "ghpr",
    "rar",
    "cpc_index",
    "serenity_index",
    "risk_of_ruin",
    "adjusted_sortino",
    "smart_sharpe",
    "smart_sortino",
    "sqn",
    "expectancy",
    "k_ratio",
    # Reports
    "MetricsReport",
    "full_metrics",
    "metrics_summary",
    "generate_html_report",
    "save_html_report",
]
